name: Build and deploy Node.js app to Azure Web App - ecommerce-backend-himanshu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la Backend || echo "Backend directory not found"
<<<<<<< HEAD
          ls -la frontend || echo "frontend directory not found"
          find . -type f -name "*.html" -o -name "*.js" -o -name "*.json" -o -name "*.yml"
=======
          ls -la Frontend || echo "frontend directory not found"
>>>>>>> 6609fb118cbca5b8bff5cefe9ef9c924835f3b4d
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: npm install, build, and test
        working-directory: Backend
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
      - name: Verify frontend files
        run: |
          if [ ! -d "frontend" ]; then
            echo "Error: frontend directory missing!"
            exit 1
          fi
          if [ ! -f "frontend/index.html" ]; then
            echo "Error: frontend/index.html missing!"
            exit 1
          fi
          if [ ! -f "frontend/cart.html" ]; then
            echo "Error: frontend/cart.html missing!"
            exit 1
          fi
          if [ ! -f "frontend/script.js" ]; then
            echo "Error: frontend/script.js missing!"
            exit 1
          fi
      - name: Zip artifact for deployment
        run: |
          zip -r release.zip Backend/ frontend/
<<<<<<< HEAD
      - name: List zip contents
        run: unzip -l release.zip
=======
>>>>>>> 6609fb118cbca5b8bff5cefe9ef9c924835f3b4d
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      - name: Unzip artifact for deployment
        run: unzip release.zip
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3E4D2CF697E484F8070C45BFD962135 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_69F0EAC5BEBE463F9C0EBAE4A7467911 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69084CDE3B18453EA3B6AF927416F82F }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ecommerce-backend-himanshu'
          slot-name: 'Production'
          package: .